### ISSUE TITLE
How to delay token?

### ISSUE THREAD

**Issue by zqtlin** [miguelgrinberg/REST-auth#11]
How to automatically postpone the token after receiving the request？

**Comment by miguelgrinberg** [comment]
What do you mean by "postpone"?

**Comment by zqtlin** [comment]
When I received the request, the original token timestamp could be renewed. For example, the token time I set was half an hour. After 15 minutes, when I received the request, I updated the token timestamp and set it in half an hour before token failed.

**Comment by miguelgrinberg** [comment]
This type of token cannot be extended, if you want to give the client more time, then you need to generate a new token with the updated expiration time.

**Comment by zqtlin** [comment]
OK.Thanks for your reply!
