### ISSUE TITLE
ModuleNotFoundError "pysqllite2"

### ISSUE THREAD

**Issue by puru-cr7** [miguelgrinberg/REST-auth#14]
unable to launch app, getting ModuleNotFoundError "pysqllite2" on db.create_all

**Comment by miguelgrinberg** [comment]
Did you compile Python yourself? You are missing stuff, such as sqlite3.

**Comment by puru-cr7** [comment]
I did a pip on requirements.txt
Was getting module not found for pysqlite2
rNow I removed all the versions from requirments.txt and did a pip again and it started working.
Please, note I am using python 3.6
If the dependencies are for 2.7 then please add a line on the readme.
By the way, the code is well explained.

**Comment by miguelgrinberg** [comment]
I'm talking about your Python interpreter, this isn't about dependencies. Did you compile it yourself? If not, from where did you get it?

**Comment by miguelgrinberg** [comment]
The dependencies work for 2.7 and 3.5+, they are all the same. You must have had something in your virtualenv that affected the sqlite module. I first thought you may have a Python compiled w/o sqlite support, which is what usually happens when you compile the interpreter yourself.

**Comment by puru-cr7** [comment]
Please see screen shot
![screenshot](https://user-images.githubusercontent.com/17329626/52005918-de30c580-24f0-11e9-8b9e-32cbfc2eafa1.jpg)

**Comment by puru-cr7** [comment]
I exactly followed the steps in README.md

**Comment by miguelgrinberg** [comment]
And sqlite3 is not a dependency, it is part of Python, but in your installation it appears to be broken.

**Comment by puru-cr7** [comment]
Yes, you are tight. That is what is happening. But if I run it directly it works, that is without virtual env. So why is it that virtual env creation would break this library?

**Comment by miguelgrinberg** [comment]
Maybe your virtualenv is configured to not look for packages in the system wide python? Unfortunately I don't use conda, so I really don't know if this is common or some problem with your installation. Odd that I never heard about it though, I have seen a fare share of conda users doing my tutorials.
