### ISSUE TITLE
Could flask be detecting request is coming from a browser and always returning 200 status despite invalid credentials?

### ISSUE THREAD

**Issue by gr-satt** [miguelgrinberg/REST-auth#16]
Hi, 

First of all thank you so much for releasing this. I am using this to authenticate users for my first web app. 

When I am making login requests from the command line, python, and node I get 401 status for invalid credentials just as I should. But when i run and test locally in browser I always get 200 for some odd reason. I also cant find anything online about anyone having a similar issue and have tried posting on SO ([here](https://stackoverflow.com/questions/58146747/making-rest-post-request-always-returning-200-despite-wrong-credentials?noredirect=1#comment102721725_58146747)) to no avail. Has anyone here had this happen?

**Comment by miguelgrinberg** [comment]
Have you added prints to find out what is the server seeing? This should be pretty easy to figure out once you see what username and password the server is receiving I think.

**Comment by gr-satt** [comment]
yes. so I am making the login request to api/resources on html button onclick action like this: 

`   <button id="loginButton" onclick="login_user()">login</button>

    <script type="text/javascript">
    function login_user() {
        let path = "http://127.0.0.1:5000/api/resource";
        let user_input = document.getElementById("user").value;
        let pass_input = document.getElementById("pass").value;

        let data = {username:user_input, password:pass_input};

        fetch(path, {
            headers: {
                "Content-Type": "application/json"},
            method: "POST",
            body: JSON.stringify(data)}
        ).then((response) => {
            // success -- redirect to welcome
            if (response.status == 200) {
                window.location.href = "http://127.0.0.1:5000/welcome"
            // retry 
            } else {
                window.location.href = "http://127.0.0.1:5000/login"
            }
    });
        };
    </script>`

then i am running the app and i enter 'invaliduser' and 'invalidpass' into the username and password forms and it returns a 200 and will redirect me to the welcome page. I am attaching screenshot of request from developer tools. 

![Screen Shot 2019-10-01 at 11 07 44 PM](https://user-images.githubusercontent.com/49654862/66015397-63b1ae80-e4a0-11e9-8670-92385384a091.png)

**Comment by miguelgrinberg** [comment]
I'll repeat my question. Have you added print statements in the server code to verify what username and password is the server authenticating against?
