### ISSUE TITLE
HttpBasicAuth seems to fail being deployed to heroku

### ISSUE THREAD

**Issue by fung1** [miguelgrinberg/REST-auth#17]
Hi, Miguel! I forked the repo, switched from sqlite to MySQL and deployed it on heroku, but I get 401 on the protected endpoints.
```
$ curl -u miguel:python -i -X GET https://apisrv.herokuapp.com/api/resource
HTTP/1.1 401 UNAUTHORIZED
Connection: keep-alive
Server: gunicorn/20.0.4
Date: Sun, 14 Jun 2020 14:04:59 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 19
Www-Authenticate: Basic realm="Authentication Required"
Via: 1.1 vegur

Unauthorized Access

$ curl -u miguel:python -i -X GET https://apisrv.herokuapp.com/api/token
HTTP/1.1 401 UNAUTHORIZED
Connection: keep-alive
Server: gunicorn/20.0.4
Date: Sun, 14 Jun 2020 14:05:29 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 19
Www-Authenticate: Basic realm="Authentication Required"
Via: 1.1 vegur

Unauthorized Access
```
I tested the code in virtualenv and it worked great.

My forked repo is https://github.com/fung1/REST-auth

**Comment by miguelgrinberg** [comment]
Did you create a new user on your Heroku database?

**Comment by fung1** [comment]
> Did you create a new user on your Heroku database?

MySQL responds at https://apisrv.herokuapp.com/api/users/1 correctly, I guess.

**Comment by miguelgrinberg** [comment]
I can't debug this for you, unfortunately, since I don't have access. The application is simple enough, try to verify the password from a python shell as a start. Or reset your password in your database. I can't really do anything myself, what I can tell you 100% certain this is a problem in your set up, not in the code.

**Comment by jmbajo** [comment]
Hello, I solved this issue by making the password field longer in the database. Apparently, 64 characters are not enough.

BTW, thank you Miguel for the code, very useful indeed!

Juan
